# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180406_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
