# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180430_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approve_comment',
        ),
    ]
