# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180605_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RenameField(
            model_name='citypost',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='citypost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citypost',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
