# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180605_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='citypost',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
