# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_citypost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('street', models.TextField()),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.City')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('street', models.TextField()),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.City')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='Airport',
        ),
    ]
