# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 08:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180605_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='railwaystation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
        migrations.AddField(
            model_name='airport',
            name='city_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CityPost'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='city_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CityPost'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='city_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CityPost'),
        ),
        migrations.AddField(
            model_name='railwaystation',
            name='city_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CityPost'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CityPost'),
        ),
    ]
