# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_visitpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='visit_points',
            field=models.ManyToManyField(blank=True, to='blog.VisitPoint'),
        ),
    ]
