# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_dayplan_visit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitpoint',
            name='must_see',
            field=models.BooleanField(default=False),
        ),
    ]
