# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180613_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='railwaystation',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitpoint',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
